baseurl = "https://example.com/"  # Include trailing slash
title = "dnd-qodqks's blog"
theme = "newsroom"
canonifyurls = true
paginate = 6

[permalinks]
  pages = ':filename/'

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"
