baseurl = "https://example.com/"  # Include trailing slash
title = "dnd-qodqks's blog"
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = "newsroom"
author = "dnd-qodqks"
canonifyurls = true
paginate = 6

[permalinks]
  pages = ':filename/'

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"
