baseURL = 'https://dnd-qodqks.github.io/'
languageCode = 'en-us'
title = 'dnd-qodqks blog'
theme = "newsroom"
author = "dnd-qodqks"
canonifyurls = true
paginate = 6

[permalinks]
  pages = ':filename/'

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"
